### ISSUE TITLE
3-letter agency Player monitoring

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/CivSpy#1]
Taken from https://github.com/ProgrammerDan/CivSpy/issues/1

as part of civspy, could you determine block break count / rate and movement for a player while in a chunk?

so, for these 5 minutes and this player, chunk X 500 breaks active rate 10.0/sec moved 100 blocks, chunk Y 2 breaks rate 0.1/sec moved 1000 blocks

ultimately I'd like to be able to graph a player's movement across a server and see hot spots of activity

chunk resolution is fine

there may be other interesting stats to track at that level

**Comment by ProgrammerDan** [comment]
Thoughts:

Per sample period record:
- break.count.chunk / { uuid }_{ world }_{ chunkx }_{ chunkz } / aggregate #
  - Rate is then count / sample period

Movement is harder unless I want to process every movement event which gets excessive. Could gate it ... sample diff every second, perhaps. Instead of fancy intersection math, "award" movement to origin chunk. Then write it out to db every Sample Period.
- movement.distance.chunk / { uuid }_{ world }_ { chunkx }_{ chunkz } / distance sum
  - Rate is then sum / sample period

@erocs also based on your and max's wishlists I'm thinking I'll expand the tracking db to include focuses on world / chunk / player  still with keying.

**Comment by ProgrammerDan** [comment]
This is implemented; sample event aggregators for movement and block breaks.
